sonar.projectKey=inteli-px4-cicd-demo
sonar.projectName=Inteli PX4 CI/CD Demo
sonar.projectVersion=0.1.0

sonar.sources=libs
sonar.tests=tests
sonar.exclusions=PX4-Autopilot/**,**/__pycache__/**,.venv/**,docs/**
# tools/ será adicionado no PR #2 quando o diretório existir

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
